### ISSUE TITLE
Cli version does not work on arch

### ISSUE THREAD

**Issue by Jadonus** [lighttigerXIV/catppuccinifier#18]
I get a error message of: Error generating (whatever flavor I chose)  image. I am not sure what that problem is. Also, using paru I cannot get the GUI version to build.

**Comment by lighttigerXIV** [comment]
> I get a error message of: Error generating (whatever flavor I chose) image. I am not sure what that problem is. Also, using paru I cannot get the GUI version to build.

Did you install image magick? I didn't test the aur since @isabelroses is the one maintaining it

**Comment by isabelroses** [comment]
> Did you install image magick? I didn't test the aur since @isabelroses is the one maintaining it

Thanks for notifying me, i've found the error with the gui version, the cli one i'm just about to start testing.

**Comment by isabelroses** [comment]
> I get a error message of: Error generating (whatever flavor I chose) image. I am not sure what that problem is. 

I can't seem to get this error, whenever I run it I get:
https://github.com/lighttigerXIV/catppuccinifier/issues/18#issue-1732575916

**Comment by Jadonus** [comment]
Strange. Imagemagick is installed, just used it to convert an image today. Would a specific version be needed?

**Comment by isabelroses** [comment]
> Would a specific version be needed?

not that i know of, ive always been using the latest version of it on the arch repos.

From what i know this project has no verbose mode. 
Perhaps can you check `~/.local/share/catppuccinifier`

**Comment by lighttigerXIV** [comment]
> Strange. Imagemagick is installed, just used it to convert an image today. Would a specific version be needed?

In last case i can update it to show what error is :skull:

**Comment by Jadonus** [comment]
Checking ~/.local/share/catppuccinifier gives me  patterned images. Not what I need obviously.

**Comment by isabelroses** [comment]
> Checking ~/.local/share/catppuccinifier gives me patterned images. Not what I need obviously.

No that's exactly correct, there called luts, I'm guessing their under a directory called `flavours` which means thats not the issue.

**Comment by isabelroses** [comment]
> Yes, except spelled flavors. Hmm

That would be my bad i can't spell `flavors` is the correct spelling

**Comment by Jadonus** [comment]
I was able to get the gui version installed, but it gives me a connection refused error. Sigh.

**Comment by isabelroses** [comment]
> I was able to get the gui version installed, but it gives me a connection refused error. Sigh.

Yeah i just updated it, but connection error I don't think that's something i can fix.

**Comment by Jadonus** [comment]
Ok. I’ll try it later and hopefully it works.
