### ISSUE TITLE
add support for alpha channel

### ISSUE THREAD

**Issue by kingofcube** [lighttigerXIV/catppuccinifier#34]
when i put in an image that has a transparent layer (like the background), it just makes the layer the base color

**Comment by lighttigerXIV** [comment]
> when i put in an image that has a transparent layer (like the background), it just makes the layer the base color

If you want something like that you should discuss that in the [lutgen issues](https://github.com/ozwaldorf/lutgen-rs)

**Comment by kingofcube** [comment]
> > when i put in an image that has a transparent layer (like the background), it just makes the layer the base color
> 
> If you want something like that you should discuss that in the [lutgen issues](https://github.com/ozwaldorf/lutgen-rs)

oh k

**Comment by Jas-SinghFSU** [comment]
Seems that there is a "working" WIP branch https://github.com/ozwaldorf/lutgen-rs/compare/transparency...main. Is it possible to create a transparency branch here that we can build with until it's merged into main branch?

**Comment by kingofcube** [comment]
> Seems that there is a "working" WIP branch [ozwaldorf/lutgen-rs@transparency...main](https://github.com/ozwaldorf/lutgen-rs/compare/transparency...main). Is it possible to create a transparency branch here that we can build with until it's merged into main branch?

Sure whynot.
